### ISSUE TITLE
1.9.7 fails to add an annotation with a required attribute (works on 1.8.1)

### ISSUE THREAD

**Issue by rebarbora-mckvak** [eclipse-aspectj/aspectj#105]
I have a following annotations and aspect in a library (already compiled):

```java
@Target({ElementType.TYPE})
@Retention(RetentionPolicy.RUNTIME)
public @interface BarAnnotation {
    
    // Note the attribute does not have any default value.
    String name();
}
```
```java
@Target({ElementType.TYPE})
@Retention(RetentionPolicy.RUNTIME)
public @interface FooAnnotation {
}
```
```java
public aspect FooAspect {
    declare @type:(@FooAnnotation *): @BarAnnotation(name = "comes_from_FooAspect");
}
```

Then I compile a source of a class in the main program (using the aspect and annotations from the library):

```java
// FooAspect is supposed to add @BarAnnotation(value = "comes_from_FooAspect")
@FooAnnotation
public class MyFoo {
}
```

This works using aspectj 1.8.1, but fails on 1.9.7 with the error *The annotation @BarAnnotation must define the attribute value*. Both versions of ajc do the following:

1. @BarAnnotation() is added to MyFoo - note the name attribute is missing - this is done by AjLookupEnvironment.createAnnotationFromBcelAnnotation
2. the class is compiled into bytecode- succeeds on 1.8.1, fails on 1.9.7 (the annotation is missing an attribute value)
3. AjPipeliningCompilerAdapter.afterProcessing calls queueForWeaving which "fixes" the annotation on 1.8.1, 1.9.7 does not call the weaver at all, because the compilation in step 2 failed.

**Comment by kriegaex** [comment]
I cannot reproduce the problem. I compiled and ran with AspectJ 1.8.1, 1.9.7, 1.9.8.RC2, using `dev.aspectj:aspectj-maven-plugin:1.13.1`, using Java 1.8 compliance level. Can you please explain in more detail how you compiled that code?

BTW, in this comment

```java
// FooAspect is supposed to add @BarAnnotation(value = "comes_from_FooAspect")
@FooAnnotation
```

you probably mean `name =`, rather than `value =`, do you not?

**Comment by rebarbora-mckvak** [comment]
I added a test to github:

```bash
git clone https://github.com/rebarbora-mckvak/aspectjtest.git
cd aspectjtest
export JAVA_HOME=/usr/lib/jvm/java-8-jdk
mvn clean compile
...
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] aspect-project
[INFO] aspect-lib
[INFO] aspect-prog
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building aspect-project 1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ aspect-project ---
[INFO] 
[INFO] --- aspectj-maven-plugin:1.14.0:compile (ajccompile) @ aspect-project ---
[WARNING] Not executing aspectJ compiler as the project is not a Java classpath-capable package
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building aspect-lib 1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ aspect-lib ---
[INFO] Deleting /fast/literatum/source/aspectjtest/x/aspectjtest/aspect-lib/target
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ aspect-lib ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory /fast/literatum/source/aspectjtest/x/aspectjtest/aspect-lib/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ aspect-lib ---
[INFO] Changes detected - recompiling the module!
[WARNING] File encoding has not been set, using platform encoding UTF-8, i.e. build is platform dependent!
[INFO] Compiling 2 source files to /fast/literatum/source/aspectjtest/x/aspectjtest/aspect-lib/target/classes
[INFO] 
[INFO] --- aspectj-maven-plugin:1.14.0:compile (ajccompile) @ aspect-lib ---
[INFO] Showing AJC message detail for messages of types: [error, warning, fail]
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building aspect-prog 1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ aspect-prog ---
[INFO] Deleting /fast/literatum/source/aspectjtest/x/aspectjtest/aspect-prog/target
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ aspect-prog ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory /fast/literatum/source/aspectjtest/x/aspectjtest/aspect-prog/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ aspect-prog ---
[INFO] Changes detected - recompiling the module!
[WARNING] File encoding has not been set, using platform encoding UTF-8, i.e. build is platform dependent!
[INFO] Compiling 1 source file to /fast/literatum/source/aspectjtest/x/aspectjtest/aspect-prog/target/classes
[INFO] 
[INFO] --- aspectj-maven-plugin:1.14.0:compile (ajccompile) @ aspect-prog ---
[INFO] Showing AJC message detail for messages of types: [error, warning, fail]
[ERROR] The annotation @BarAnnotation must define the attribute name
	/fast/literatum/source/aspectjtest/x/aspectjtest/aspect-prog/src/main/java/MyFoo.java:1
(no source information available)
```
It fails using both JDK 8 and JDK 11. If you use 1.8.1 with JDK 8 (JDK 11 is probably not supported by 1.8.1), it works:

```
mvn -Daspectj.version=1.8.1 clean compile
...
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] aspect-project
[INFO] aspect-lib
[INFO] aspect-prog
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building aspect-project 1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ aspect-project ---
[INFO] 
[INFO] --- aspectj-maven-plugin:1.14.0:compile (ajccompile) @ aspect-project ---
[WARNING] Not executing aspectJ compiler as the project is not a Java classpath-capable package
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building aspect-lib 1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ aspect-lib ---
[INFO] Deleting /fast/literatum/source/aspectjtest/x/aspectjtest/aspect-lib/target
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ aspect-lib ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory /fast/literatum/source/aspectjtest/x/aspectjtest/aspect-lib/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ aspect-lib ---
[INFO] Changes detected - recompiling the module!
[WARNING] File encoding has not been set, using platform encoding UTF-8, i.e. build is platform dependent!
[INFO] Compiling 2 source files to /fast/literatum/source/aspectjtest/x/aspectjtest/aspect-lib/target/classes
[INFO] 
[INFO] --- aspectj-maven-plugin:1.14.0:compile (ajccompile) @ aspect-lib ---
[INFO] Showing AJC message detail for messages of types: [error, warning, fail]
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building aspect-prog 1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ aspect-prog ---
[INFO] Deleting /fast/literatum/source/aspectjtest/x/aspectjtest/aspect-prog/target
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ aspect-prog ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory /fast/literatum/source/aspectjtest/x/aspectjtest/aspect-prog/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ aspect-prog ---
[INFO] Changes detected - recompiling the module!
[WARNING] File encoding has not been set, using platform encoding UTF-8, i.e. build is platform dependent!
[INFO] Compiling 1 source file to /fast/literatum/source/aspectjtest/x/aspectjtest/aspect-prog/target/classes
[INFO] 
[INFO] --- aspectj-maven-plugin:1.14.0:compile (ajccompile) @ aspect-prog ---
[INFO] Showing AJC message detail for messages of types: [error, warning, fail]
[INFO] 'MyFoo' (MyFoo.java:5) is annotated with @BarAnnotation(name = "comes_from_FooAspect") type annotation from 'foo.FooAspect' (FooAspect.aj:4)
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] aspect-project ..................................... SUCCESS [  0.897 s]
[INFO] aspect-lib ......................................... SUCCESS [  1.426 s]
[INFO] aspect-prog ........................................ SUCCESS [  0.089 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
```

**Comment by kriegaex** [comment]
Oh, I see. It does not happen if all classes are in the same module, but only if you have a multi-module situation with binary weaving, using a separate aspect library.

I found out that it works until 1.9.4 and started breaking in 1.9.5.

**Comment by rebarbora-mckvak** [comment]
The difference is in ASTNode.resolveAnnotations:

1.8.1:

```java
				annotation.recipient = recipient;
				// MERGECONFLICT:
//				// AspectJ Extension - don't re-resolve (pr211052)
//			    // old code:
//			    // annotationTypes[i] = annotation.resolveType(scope);
//			    // new code:
//			    annotationTypes[i] =(annotation.resolvedType==null?annotation.resolveType(scope):annotation.resolvedType);
//			    // End AspectJ Extension
				if (annotation.resolvedType==null) 
				annotation.resolveType(scope);
				// null if receiver is a package binding
				if (annotations != null) {
					annotations[i] = annotation.getCompilerAnnotation();
				}
```

1.9.7:

```java
				annotation.recipient = recipient;
				annotation.resolveType(scope);
				// null if receiver is a package binding
				if (annotations != null) {
					annotations[i] = annotation.getCompilerAnnotation();
				}
```
The older version does not call annotation.resolveType() - which in turn checks attributes and fails.

**Comment by kriegaex** [comment]
@aclement, can you please comment on the above finding and determine whether it is a bug and ought to be reverted or not? That old merge conflict in the comment was before my time as an AspectJ contributor, and so was AspectJ 1.9.5.

**Comment by kriegaex** [comment]
~~@rebarbora-mckvak, I analysed your Maven module setup and found that `FooAnnotation` is defined in the aspect library, but used in the program module. That means, you explicitly reference something from a library your main application ideally should be oblivious of in your code. While that is not forbidden technically, I had the idea to create a separate module containing `FooAnnotation`, which is used as a dependency by both the aspect library and the application module. Now, with clear separation of concerns, the project compiles and works fine. `BarAnnotation` (which I left in the aspect module, because it is only used there) is introduced correctly into `MyFoo`. If you would use `BarAnnotation` from the application module as well, you would also move it into the annotation module.~~

So you have ~~two~~ one possible workaround for now:
  * ~~Factor out the annotation used by both modules into a separate module, as explained above.~~
  * If you use Java compliance level <= 12, use AspectJ 1.9.4 for the moment.

**Comment by kriegaex** [comment]
> The difference is in ASTNode.resolveAnnotations:

Well, but the behaviour changed between 1.9.4 and 1.9.5, and `ASTNode` did not change in that release cycle, as you can see in the [V1_9_4...V1_9_5 diff](https://github.com/eclipse/org.aspectj/compare/V1_9_4...V1_9_5). Therefore, the root cause must be something different.

**Comment by rebarbora-mckvak** [comment]
> Now, with clear separation of concerns, the project compiles and works fine. 

@kriegaex, it does not work. The only reason why it works for you is because you added default value to that attribute.

**Comment by kriegaex** [comment]
> it does not work. The only reason why it works for you is because you added default value to that attribute.

Yes, you are right. I accidentally forgot to revert a temporary change and thought that restructuring the modules would solve the problem. I apologise for making a false statement.

So the only current workaround is to use AspectJ 1.9.4 or older.

**Comment by rebarbora-mckvak** [comment]
That is al right, I will try to look at 1.9.4 and compare it with the latest version.

**Comment by kriegaex** [comment]
Oh, OK, now I see that the source code you pasted above was not actually from AspectJ itself but from the JDT Core fork used as a dependency of AspectJ. You did not mention that, so I searched through the wrong project's diff. That one of course has changed before the 1.9.5 release. More precisely, before 1.9.7 the modified JDT Core used to be committed as binary JAR and source ZIP archives right into AspectJ, see commit https://github.com/eclipse/org.aspectj/commit/2704db20ecca12d3bbe514a4f7b84d297937de86. I changed this for 1.9.7 and made it a regular Maven dependency.

The commit in the old `org.aspectj.shadows` repository which changed the source code area you were hinting at is [this one](https://git.eclipse.org/c/aspectj/org.aspectj.shadows.git/diff/org.eclipse.jdt.core/compiler/org/eclipse/jdt/internal/compiler/ast/ASTNode.java?h=aj_19&id=9dc0d904ee04d79dc40d2fd7b758c7b9e8a4b822). I just found it in the legacy Git repository. OK, so chances are that reverting the removal of that line of code might actually fix this problem. I have, however, no idea if it might break anything else. I could just build the JDT Core fork and run the AspectJ test suite when depending on it. But that alone would not give me confidence that we are doing the right thing. I still would like to get @aclement's opinion.

**Comment by rebarbora-mckvak** [comment]
It is the change in org.aspectj.org.eclipse.jdt.internal.compiler.ast.ASTNode which very likely comes from org.eclipse.jdt.core/jdtcore-for-aspectj.jar. I looked at its source in eclipse jdt repo, but I could not find the version matching the code used in <=1.9.4 there (none of the versions I looked at had the `if (annotation.resolvedType==null) `). Perhaps it was patched a bit for <=1.9.4, but it was not patched for later versions.

**Comment by rebarbora-mckvak** [comment]
> if it might break anything else.

Yeah, I know the feeling ;-). Thanks for looking at it either way. I will try 1.9.4 for now since we target jdk 11.

**Comment by kriegaex** [comment]
> @aclement, can you please comment on the above finding and determine whether it is a bug and ought to be reverted or not? That old merge conflict in the comment was before my time as an AspectJ contributor, and so was AspectJ 1.9.5.

@aclement, please take a look at JDT Core. In class `org.eclipse.jdt.internal.compiler.ast.ASTNode`, I experimentally reverted the removal of `if (annotation.resolvedType == null)` you did for 1.9.5, but it has no effect on the test case. The same error still occurs. So this piece of code is not the problem or only part of it.

I have added a test case to the AspectJ 1.9.8 test suite, almost identical to the code above. It fails with both JDT Core 1.9.8.RC2 and a local version 1.9.8.RC3 with the change. When the bug is fixed, it should pass, however.

**Comment by kriegaex** [comment]
> In class `org.eclipse.jdt.internal.compiler.ast.ASTNode`, I experimentally reverted the removal of `if (annotation.resolvedType == null)` you did for 1.9.5, but it has no effect on the test case. The same error still occurs.

Good news: I just retested this, and now JDT Core 1.9.8.RC3 fixes the problem while 1.9.8.RC2 does not. For some reason, during my first test somehow the IDE must have missed to pick up the updated dependency version in my POM. Now I am just hoping that the change does not break any other tests. I am going to deploy a JDT Core snapshot to OSSRH first, then run a GitHub CI build against it. If (and only if) it is green, I am going to deploy 1.9.8.RC3 versions of both JDT Core and AspectJ on Maven Central. Stay tuned.

**Comment by kriegaex** [comment]
AspectJ 1.9.8.RC3 is available on Maven Central. It should fix your problem, please re-test. Thank you.

**Comment by kriegaex** [comment]
@rebarbora-mckvak, I would appreciate some feedback. I tried to fix this problem ASAP and do appreciate your initial pointers about the potential root cause. So let us get this off the table, shall we? 🙂

**Comment by aclement** [comment]
Glad you got to the bottom of that. Annotation resolution in JDT can trip up with the way AspectJ stretches things (with features like `declare @`) - it is not uncommon to need guards like this. It is a shame we didn't have a test earlier that verified the need.

**Comment by kriegaex** [comment]
> Glad you got to the bottom of that.

Great detective work by @rebarbora-mckvak.

**Comment by rebarbora-mckvak** [comment]
It seems to work correctly, I will try to compile the real project with 1.9.8.RC3 ASAP and let you know. Our aspect adds some Hibernate's caching-related annotations. One of those, @Cache has mandatory `usage` attribute and caused problems.
