### ISSUE TITLE
Annotation style syntax not behaving like docs describe for if()

### ISSUE THREAD

**Issue by aclement** [eclipse-aspectj/aspectj#115]
Here https://www.eclipse.org/aspectj/doc/released/adk15notebook/ataspectj-pcadvice.html it says 

```
The special forms if(true) and if(false) can be used in a more general way and don't imply that 
the pointcut method must have a body. You can thus write @Before("somePoincut() && if(false)") .
```

But you can't, it won't compile. It looks like the validator for annotation style was not finished to cover the special cases

**Comment by kriegaex** [comment]
Cool! I noticed that before a while ago, but forgot to inquire about it or mention it.
