### ISSUE TITLE
Enable LTW in JDK 16+ without `--add-opens`

### ISSUE THREAD

**Issue by kriegaex** [eclipse-aspectj/aspectj#117]
Since 1.9.7, the AspectJ release notes say:

> ### Use LTW on Java 16+
> Please note that if you want to use load-time weaving on Java 16+, the weaving agent collides with [JEP 396 (Strongly Encapsulate JDK Internals by Default)](https://openjdk.java.net/jeps/396). Therefore, you need to set the JVM parameter `--add-opens java.base/java.lang=ALL-UNNAMED` in order to enable aspect weaving. This is due to the fact that the weaver uses internal APIs for which we have not found an adequate replacement yet when defining classes in different classloaders.

@aclement, do you have any ideas how to solve this?

See also:
  * https://bugs.eclipse.org/bugs/show_bug.cgi?id=546305
  * https://bugs.openjdk.java.net/browse/JDK-8200559

Maybe taking a look at how other tools like Byte Buddy or Javassist try to define classes in other class-loaders can be helpful, e.g. https://github.com/jboss-javassist/javassist/blob/master/src/main/javassist/util/proxy/DefineClassHelper.java.

**Comment by aclement** [comment]
> @aclement, do you have any ideas how to solve this?

nope.

**Comment by KillerJmc** [comment]
This is a big issue. I don't want to write this to my vm option.

**Comment by kriegaex** [comment]
> I don't want to write this to my vm option.

@KillerJmc, nobody does. But it is necessary. Feel free to either complain to the OpenJDK team, to suggest a technically viable strategy to solve the problem or provide a pull request. Alternatively, use compile-time instead of load-time weaving.

Hi @mlchung, is [JDK-8200559](https://bugs.openjdk.org/browse/JDK-8200559) still scheduled to be fixed in JDK 21? If so, can you please elaborate on how we could in the future use the corresponding new JDK feature? You were talking about this issue with AspectJ project lead @aclement before in [Bugzilla 546305](https://bugs.eclipse.org/bugs/show_bug.cgi?id=546305). This is still a major issue for byte code engineering tools such as Byte Buddy or AspectJ.

**Comment by kriegaex** [comment]
We finally have a solution for this, and I am actually a little bit proud of the achievement, even though part of the credit goes to Byte Buddy, where I found something to adapt into AspectJ, but using ASM directly instead (which is also used under the hood in BB, even though not so visible in the code there). The relevant code sections in `ClassLoaderWeavingAdaptor` were overhauled and streamlined.

What I am not proud of is that we still need `Unsafe`. But [JDK-8200559](https://bugs.openjdk.org/browse/JDK-8200559) is still open and unsolved since 2018, going on 6 years now. I kicked off some new discussion on GitHub in a related PR, which also led to new mailing list discussion triggered by Rafael Winterhalter (author of Byte Buddy). The solution he originally devised in his PR would have been simple to adapt by AspectJ. The one he suggests now is much more complicated to satisfy module security concerns by the JDK team. I think, it would be quite a nightmare for us to adapt, but on top of that the present solution would still stay in AspectJ for a long time, because the existing JDKs do not have that hypothetical new API.

**Comment by kriegaex** [comment]
@aclement, what I have no idea about is whether LTW used to work on GraalVM (never tried using it) before and, if so, it would still work after this change. Maybe you or one of your team mates could verify this. It might have an impact on Spring Native too, I have no idea.

**Comment by KillerJmc** [comment]
**Wow! Awesome! Please notify me when the new version is released.**

**Comment by kriegaex** [comment]
You should not expect me to personally notify you of a new release. I already send notifications to the AspectJ users and announcements mailing lists, and you can easily subscribe to GitHub releases using the "Watch" button and then customise the notifications of your choice.

![image](https://github.com/eclipse-aspectj/aspectj/assets/1537384/c994149f-c29a-4c69-82e4-f9472240f1f7)
---
![image](https://github.com/eclipse-aspectj/aspectj/assets/1537384/5803fd66-6e32-4fea-9d98-20274b42b8e7)

Please also refrain from needless full quotes. I just edited your post. Thank you.
