### ISSUE TITLE
Aspectj 1.9.8 is not backward compatible with JDK 8 - java.lang.UnsupportedClassVersionError: org/eclipse/core/runtime/OperationCanceledException

### ISSUE THREAD

**Issue by rohitgaikwad09** [eclipse-aspectj/aspectj#124]
Hi Team,

The backward compatibility below issue with JDK 8 occurs only with 1.9.8 version of AspectJ. 

**Steps to reproduce the issue:**
**1)** Set JDK-8 and verify JDK-8 version in cmd.exe.
**2)** Download aspectjtools.jar from maven.
**2)** execute command -> `java -cp aspectjtools.jar org.aspectj.tools.ajc.Main -g -d .`

**Exception stack:**
`D:\new-1.9.8\lib>java -cp aspectjtools.jar org.aspectj.tools.ajc.Main -g -d .`
` Exception in thread "main" java.lang.UnsupportedClassVersionError:
  org/eclipse/core/runtime/OperationCanceledException has been compiled by a more recent version of 
  the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file 
  versions up to 52.0`
        `at java.lang.ClassLoader.defineClass1(Native Method)`
        `at java.lang.ClassLoader.defineClass(Unknown Source)`
        `at java.security.SecureClassLoader.defineClass(Unknown Source)`
        `at java.net.URLClassLoader.defineClass(Unknown Source)`
        `at java.net.URLClassLoader.access$100(Unknown Source)`
        `at java.net.URLClassLoader$1.run(Unknown Source)`
        `at java.net.URLClassLoader$1.run(Unknown Source)`
        `at java.security.AccessController.doPrivileged(Native Method)`
        `at java.net.URLClassLoader.findClass(Unknown Source)`
        `at java.lang.ClassLoader.loadClass(Unknown Source)`
        `at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)`
        `at java.lang.ClassLoader.loadClass(Unknown Source)`
        `at org.aspectj.tools.ajc.Main.runMain(Main.java:230)`
        `at org.aspectj.tools.ajc.Main.main(Main.java:84)`

`D:\new-1.9.8\lib>java -version`
`java version "1.8.0_301"`
`Java(TM) SE Runtime Environment (build 1.8.0_301-b25)`
`Java HotSpot(TM) 64-Bit Server VM (build 25.301-b25, mixed mode)`

**Note:** 

1. The above command does not results into java version compatibility related error with JDK-11 and AspectJ 1.9.**8**.  
2. The above command does not results into java version compatibility related error with JDK-8 and AspectJ 1.9.**7**.

As the class is compiled with Java 11, there is no workaround to use it with Java 8.
Can someone please take a look into this?

Thanks,
            --Rohit

**Comment by kriegaex** [comment]
Please refer to the [AspectJ 1.9.8 release notes](https://htmlpreview.github.io/?https://github.com/kriegaex/org.aspectj/blob/4b9d86acd096e5ee9e108ff0a450c420c880b6ea/docs/dist/doc/README-198.html), section "Other changes and bug fixes":

> The AspectJ compiler `ajc` (contained in the `aspectjtools` library) no longer works on JDKs 8 to 10. The minimum compile-time requirement is now JDK 11 due to upstream changes in the Eclipse Java Compiler (subset of JDT Core), which AspectJ is a fork of. You can still compile to legacy target versions as low as Java 1.3 when compiling plain Java code or using plain Java ITD constructs which do not require the AspectJ runtime `aspectjrt`, but the compiler itself needs JDK 11+. Just like in previous AspectJ versions, both the runtime `aspectjrt` and the load-time weaver `aspectjweaver` still only require JRE 8+.

Having said that, please understand that in order to run your compiled AspectJ application, you simply need `aspectjrt` on the classpath, not `aspectjtools`. The latter is only needed during build time. So you you can relax: Just compile your aspects on Java 11+, but then happily run them on Java 8. Or if you use LTW in combination with annotation-style aspects, you can compile everything with `javac` (also on JDK 8, if you like) and then finish the aspects with `aspectjweaver`.

@aclement, this issue can be closed as invalid.
