### ISSUE TITLE
Renovate or remove AspectJ Browser

### ISSUE THREAD

**Issue by kriegaex** [eclipse-aspectj/aspectj#148]
Maybe the AspectJ Browser is or used to be a helpful tool. Never having used it myself, I am not sure if it is worth keeping it around in the AspectJ repository and documentation. If we do want to keep it, I think we have to bring it up to date first. So we need a decision here and then act according to it.

Here is a collage of what it looks like:

![image](https://user-images.githubusercontent.com/1537384/161288724-d7259b45-bf92-4b0f-8111-a5fb229ae241.png)

You see the maximum of Java 1.6 here. That indicates when it might have updated the last time. I have browsed the commit history of folder [ajbrowser](https://github.com/eclipse/org.aspectj/tree/master/ajbrowser). Other than version bumps or Java version syntax upgrades (e.g. using generics or some new JDK API), the last functional changes have been at least a dozen years or so ago.

@aclement, what is your opinion about AJ Browser?

**Comment by aclement** [comment]
I think it can be retired safely

**Comment by kriegaex** [comment]
@aclement, can you please also explain briefly what this AJDE stuff is supposed to be? Was that only for JBuilder and can also be removed, or is it somehow used indirectly by AJDT?
