### ISSUE TITLE
AspectJ Internal Error: unable to add stackmap attributes. Unsupported class file major version 61

### ISSUE THREAD

**Issue by Ashish-Pandey-Imprivata** [eclipse-aspectj/aspectj#175]
When trying to use AspectJ version 1.9.9 (or 1.9.9.1) with JDK 17, I am getting below error:

AspectJ Internal Error: unable to add stackmap attributes. Unsupported class file major version 61

I have seen related errors that report issue with "version 58" or "version 60" etc e.g. https://bytemeta.vip/repo/allure-framework/allure2/issues/1378, but haven't found how to resolve this JDK17 specific issue.

**Comment by kriegaex** [comment]
Please add a link to a project reproducing the problem. Thank you. I cannot debug prose without code. My preliminary working hypothesis is that somehow am older AspectJ compiler version has crept into your build.

**Comment by kriegaex** [comment]
@Ashish-Pandey-Imprivata, because you did not respond within 11 days after I responded the very same day you created the issue, I am closing this issue as invalid. I will consider reopening it, if you provide the MCVE I requested.
