### ISSUE TITLE
Looks like the artifact name got changed in the most recent release

### ISSUE THREAD

**Issue by chenrui333** [eclipse-aspectj/aspectj#202]
👋  it looks like the artifact name got changed from `aspect-#{version}.jar` into `installer-#{version}.jar`. Wouldn't `aspect-#{version}.jar` be better? Thanks!

**Comment by kriegaex** [comment]
> `aspect-#{version}.jar`

You probably mean `aspectj-#{version}.jar` with a "j" in the middle. Actually, not the (Maven) artifact name has changed, it was always `installer`. What has changed is that I forgot to manually rename it during the upload to the GitHub release. Good catch, though. 👏🙂

I have just renamed the file, it should be OK now.

**Comment by chenrui333** [comment]
> > `aspect-#{version}.jar`
> 
> You probably mean `aspectj-#{version}.jar` with a "j" in the middle. Actually, not the (Maven) artifact name has changed, it was always `installer`. What has changed is that I forgot to manually rename it during the upload to the GitHub release. Good catch, though. 👏🙂
> 
> I have just renamed the file, it should be OK now.

yeah, `aspectj` not `aspect`. Thanks for the rename!!
