### ISSUE TITLE
aspectjweaver not working properly with jdk17

### ISSUE THREAD

**Issue by jvyas24** [eclipse-aspectj/aspectj#262]
info deactivating aspect 'org.springframework.cache.aspectj.JCacheCacheAspect' as it requires type 'javax.cache.annotation.CacheResult' which cannot be found on the classpath

**Comment by kriegaex** [comment]
What makes you think that this is an AspectJ problem? Where is your reproducer project? We can reopen the issue, if you give me reason to believe that the problem is not sitting in front of the computer in this case.
