### ISSUE TITLE
WeavingAdaptor optimisations cause Equinox weaving problems

### ISSUE THREAD

**Issue by kriegaex** [eclipse-aspectj/aspectj#305]
A contribution by @urisimchoni for AspectJ 1.9.21.1 fixed problem #279, but introduced a new one downstream in Eclipse when using Equinox OSGi weaving via AJDT, see https://github.com/eclipse-aspectj/ajdt/issues/57.

Part of the PR needs to be reverted so as to still keep the AspectJ fix intact while not messing up Equinox weaving.

**Comment by urisimchoni** [comment]
@kriegaex on first glance it appears like this revert doesn't break #279. I removed the generated class keys because I thought they were not needed, not because they somehow interfere with fixing #279. Do you agree?

**Comment by kriegaex** [comment]
@urisimchoni, it seems as if you are right. My test results in AspectJ and AJDT are looking good.
