### ISSUE TITLE
Eliminate binaries from Git repository

### ISSUE THREAD

**Issue by kriegaex** [eclipse-aspectj/aspectj#40]
**Situation:** In AspectJ we have the `lib` folder with several binary and source JARs (mostly old legacy versions) and a full (unpacked) Ant 1.6.3 installation. Futhermore there is the modified version of JDT Core, created in the separate "shadows" project and copied into the AspectJ folder by an Ant script from there. 

**Goal:** We should get rid of those binaries and instead modify the Maven build in such a way that
  * it downloads them from Maven Central if they prove to be existing artifacts available from there,
  * it downloads them from other official sources (e.g. Apache download server for Ant binary and source distributions),
  * if unavailable, deploy them to a Maven repository - not necessarily Maven Central but something we (e.g. @aclement, @kriegaex, an Eclipse admin) control and let Maven get them from there.
  * After download, the build (unpacks and) copies them to the exact location in `libs` where several scripts expect them to be.
  * If any binaries are not used by scripts but only as Maven dependencies, replace the existing system-scoped dependencies with hard-coded paths by normal Maven dependencies, fixing the transitivity problem and warnings presently caused by system dependencies, forcing us to redundantly add those dependencies to modules which normally should get them as transitive dependencies of other AspectJ modules.

I am planning to implement this myself step by step in my fork - probably on top of the existing Java 15+16 branch - and then make them part of PR #39. The reason for not doing it separately is that said branch contains many fixed tests and the build is currently green on Java 8, 11, 16. So if I break anything, it is easy to notice.

I am going to document my findings concerning "project archeology" here in additional comments, so if one day Andy or someone from Eclipse conducts a review about what seem to be new dependencies, it is clear that we had them before and just explanted them from the SCM (where they did not belong in the first place) to external sources.

**Comment by kriegaex** [comment]
The first thing I did was to create SHA-1 checksums of all JAR and ZIP files in 'libs' and then use the Maven Central search API in order to search for existing artifacts matching those checksums. Any match would prove that the corresponding artifact is available on Maven Central.

This is the script I used:

```bash
#!/usr/bin/bash

curl -s https://search.maven.org/solrsearch/select?q=1:72abc87d5f8063e74ee0cf6ae77f07ed906aeb47&rows=20
curl -s https://search.maven.org/solrsearch/select?q=1:670b30f2f251fbf566c6a66d46f892e83aff75f6&rows=20
curl -s https://search.maven.org/solrsearch/select?q=1:43a7344b27e5249c7bc896489b90ba6db0dca7b6&rows=20
curl -s https://search.maven.org/solrsearch/select?q=1:54beaa506f15126e6e2efcd202237f70d6d575b7&rows=20
curl -s https://search.maven.org/solrsearch/select?q=1:f91b166c2d4b8298b859920bb6967b25b3752734&rows=20
curl -s https://search.maven.org/solrsearch/select?q=1:0a696ad41efc75c2940b54a3e011e90ac336ab47&rows=20
curl -s https://search.maven.org/solrsearch/select?q=1:4187c036fa132781d3a7e796ba66cac55052a616&rows=20
curl -s https://search.maven.org/solrsearch/select?q=1:89cd7f7a7f026f147688627b3d4a8090990703e7&rows=20
curl -s https://search.maven.org/solrsearch/select?q=1:a712e37b7d94d1ccf4b402482afd13bd02c239fd&rows=20
curl -s https://search.maven.org/solrsearch/select?q=1:a366dd627e2803c531143d3d4d4b510ee1f90333&rows=20
curl -s https://search.maven.org/solrsearch/select?q=1:acb55eec3de47497483d80fdf0e5ed190adf2b5f&rows=20
curl -s https://search.maven.org/solrsearch/select?q=1:d37eb8033633af8a7c25afe633e9cad2cdd85f56&rows=20
curl -s https://search.maven.org/solrsearch/select?q=1:3f167cfe43245c2770d50b7069c8e3ab48919f80&rows=20
curl -s https://search.maven.org/solrsearch/select?q=1:b493bb12a8a4a8024e3771918a1ea2af1e8dcb82&rows=20
curl -s https://search.maven.org/solrsearch/select?q=1:7fc394c203e61a7981cfc71829c2e65c59229477&rows=20
curl -s https://search.maven.org/solrsearch/select?q=1:af986a1ac68c7b6c3b8320db80cc71fe044e0552&rows=20
curl -s https://search.maven.org/solrsearch/select?q=1:7ea420bdd4416ffe7d02591c17b0a2db29a828f1&rows=20
curl -s https://search.maven.org/solrsearch/select?q=1:78e3ccd9069b214c47515b5a8f04d237dab29803&rows=20
curl -s https://search.maven.org/solrsearch/select?q=1:3f1d7bfc3c05727faaed473530f5be81e4fd7258&rows=20
curl -s https://search.maven.org/solrsearch/select?q=1:7ede67c1681c144e11ab2c7041f8dcb2adfa70f9&rows=20
curl -s https://search.maven.org/solrsearch/select?q=1:a55eca413bf47f0b09b2a8a6e1dac2013ad2706c&rows=20
curl -s https://search.maven.org/solrsearch/select?q=1:0db180b2e539e9d6405383683fd0155b75aa5799&rows=20
curl -s https://search.maven.org/solrsearch/select?q=1:3e1b0f10979f62af2f439ca5fb3f6f120db90d6f&rows=20
curl -s https://search.maven.org/solrsearch/select?q=1:632615e017d035d282fa61df94bc5984274de4f1&rows=20
curl -s https://search.maven.org/solrsearch/select?q=1:b0303b04d9154365066049cdc407a2d1ef2e1e09&rows=20
curl -s https://search.maven.org/solrsearch/select?q=1:c51db8584d7cb05adcc5b0d6b4aa8207bb0e735a&rows=20
curl -s https://search.maven.org/solrsearch/select?q=1:a1300c3f922d6f24245cd19410840c57c66c1387&rows=20
curl -s https://search.maven.org/solrsearch/select?q=1:81a2e6d017b59f53ae35143c5a9b27a507500143&rows=20
curl -s https://search.maven.org/solrsearch/select?q=1:b7c953dd67e01c952d792224c6f2e281e4c1bbc7&rows=20
curl -s https://search.maven.org/solrsearch/select?q=1:99129f16442844f6a4a11ae22fbbee40b14d774f&rows=20
curl -s https://search.maven.org/solrsearch/select?q=1:897bcb56d6b7fe2070a5f561bfc78968ecdd3851&rows=20
curl -s https://search.maven.org/solrsearch/select?q=1:065acede1e5305bd2b92213d7b5761328c6f4fd9&rows=20
curl -s https://search.maven.org/solrsearch/select?q=1:0dd87297b99530431040c097f8d03764cabf08f7&rows=20
curl -s https://search.maven.org/solrsearch/select?q=1:a99500cf6eea30535eeac6be73899d048f8d12a8&rows=20
curl -s https://search.maven.org/solrsearch/select?q=1:fb6d4c045903b4d8507e9df63ae0e71aa29293fa&rows=20
curl -s https://search.maven.org/solrsearch/select?q=1:4ddaac58e669196a45ccace4a707839d04bc6771&rows=20
curl -s https://search.maven.org/solrsearch/select?q=1:45004072ea16d12d67b63d89a042a1b742c6a793&rows=20
curl -s https://search.maven.org/solrsearch/select?q=1:4e5dd843bc95657e5a7f0f4d6600a8cfeeeab4dd&rows=20
curl -s https://search.maven.org/solrsearch/select?q=1:649faa0951853ee63f8bbf5edd571d04c81c4e96&rows=20
curl -s https://search.maven.org/solrsearch/select?q=1:ba32d6d67b316bc293fe18739e5ce9306ffea1e3&rows=20
curl -s https://search.maven.org/solrsearch/select?q=1:dc3b43638c0727d0d2f77a8b8628e7f960b5d051&rows=20
curl -s https://search.maven.org/solrsearch/select?q=1:3567c76a25f49b3b733fe99d4b3482c7768840bc&rows=20
curl -s https://search.maven.org/solrsearch/select?q=1:a55eca35cc4176a1b49440b7e754ca471b614221&rows=20
curl -s https://search.maven.org/solrsearch/select?q=1:a8858b7a59beb82e7157adb668919996f59e2434&rows=20
curl -s https://search.maven.org/solrsearch/select?q=1:da817cd56c360d3f52737092ec1b54adf59f855f&rows=20
curl -s https://search.maven.org/solrsearch/select?q=1:d842ab2b81170ac5ed0051b06967ca8852530e62&rows=20
curl -s https://search.maven.org/solrsearch/select?q=1:70be878c3e948a75de1ccb20ba3b8f28c1dee9fa&rows=20
curl -s https://search.maven.org/solrsearch/select?q=1:2a645c72c70e7fd9dd4f518025b1c0ceb827ff02&rows=20
curl -s https://search.maven.org/solrsearch/select?q=1:ffa9d8eb84897746aa196d3f3336d034ddb26f59&rows=20
curl -s https://search.maven.org/solrsearch/select?q=1:7a01e7a84869e2135c0804644ddd3250b382cf0a&rows=20
curl -s https://search.maven.org/solrsearch/select?q=1:9d7d9fb3530ad2cb60517e1c22090ece4915f277&rows=20
curl -s https://search.maven.org/solrsearch/select?q=1:8190696d33f4cdc1b2f8f5821a7e9881cc27edb5&rows=20
curl -s https://search.maven.org/solrsearch/select?q=1:b81c2719c63fa8e6f3eca5b11b8e9b5ad79463db&rows=20
curl -s https://search.maven.org/solrsearch/select?q=1:4fe9ee7e627f456a4d668fa1237cb39d411d79b8&rows=20
curl -s https://search.maven.org/solrsearch/select?q=1:99129f16442844f6a4a11ae22fbbee40b14d774f&rows=20
curl -s https://search.maven.org/solrsearch/select?q=1:1a48518889a7efc4b34ebce7103d40e3b72b0965&rows=20
curl -s https://search.maven.org/solrsearch/select?q=1:1ef2d52fc0c52ab09a213d1c61f9c4072597ba1a&rows=20
curl -s https://search.maven.org/solrsearch/select?q=1:dca0bac6e2561f6ecda51ac5e4d14bb87041474e&rows=20
curl -s https://search.maven.org/solrsearch/select?q=1:6382cd1b0c4eb7693fe99ec77da106e3ea597f48&rows=20
curl -s https://search.maven.org/solrsearch/select?q=1:61c56d0847619fb955ce1a6ee30566d0579b54d5&rows=20
curl -s https://search.maven.org/solrsearch/select?q=1:3f74b24c0dcae08ee8810abb27ff59ba2fc96756&rows=20
curl -s https://search.maven.org/solrsearch/select?q=1:0525753763e53f6f76da052b316d0f2e3bfa4d73&rows=20
curl -s https://search.maven.org/solrsearch/select?q=1:183bd266951f7af52716f258de0d7d7b3d9a36ce&rows=20
curl -s https://search.maven.org/solrsearch/select?q=1:42cb1d4de348c490fff5ae37c29737b752bdb451&rows=20
curl -s https://search.maven.org/solrsearch/select?q=1:472043dc2ec6b2623c7eb1785f90663ada181df7&rows=20
curl -s https://search.maven.org/solrsearch/select?q=1:6b450d1a9a239c0f934f8c36d235277c67be9008&rows=20
curl -s https://search.maven.org/solrsearch/select?q=1:a1a0de8eaa907a12f3c0bf47e46727fd1a1d1c6d&rows=20
```

**Comment by kriegaex** [comment]
Here is the compiled result (I shortened the output in order to just contain the information we are interested in here):

```text
lib/ant/ant-src.zip                               | 
lib/ant/etc/ant-bootstrap.jar                     | 
lib/ant/lib/ant-antlr.jar                         | ant:ant-antlr:1.6.3 
lib/ant/lib/ant-apache-bcel.jar                   | ant:ant-apache-bcel:1.6.3 
lib/ant/lib/ant-apache-bsf.jar                    | ant:ant-apache-bsf:1.6.3 
lib/ant/lib/ant-apache-log4j.jar                  | ant:ant-apache-log4j:1.6.3 
lib/ant/lib/ant-apache-oro.jar                    | ant:ant-apache-oro:1.6.3 
lib/ant/lib/ant-apache-regexp.jar                 | ant:ant-apache-regexp:1.6.3 
lib/ant/lib/ant-apache-resolver.jar               | ant:ant-apache-resolver:1.6.3 
lib/ant/lib/ant-commons-logging.jar               | ant:ant-commons-logging:1.6.3 
lib/ant/lib/ant-commons-net.jar                   | ant:ant-commons-net:1.6.3 
lib/ant/lib/ant-icontract.jar                     | ant:ant-icontract:1.6.3 
lib/ant/lib/ant-jai.jar                           | ant:ant-jai:1.6.3 
lib/ant/lib/ant-javamail.jar                      | ant:ant-javamail:1.6.3 
lib/ant/lib/ant-jdepend.jar                       | ant:ant-jdepend:1.6.3 
lib/ant/lib/ant-jmf.jar                           | ant:ant-jmf:1.6.3 
lib/ant/lib/ant-jsch.jar                          | ant:ant-jsch:1.6.3 
lib/ant/lib/ant-junit.jar                         | ant:ant-junit:1.6.3 
lib/ant/lib/ant-launcher.jar                      | ant:ant-launcher:1.6.3 
lib/ant/lib/ant-netrexx.jar                       | ant:ant-netrexx:1.6.3 
lib/ant/lib/ant-nodeps.jar                        | ant:ant-nodeps:1.6.3 
lib/ant/lib/ant-starteam.jar                      | ant:ant-starteam:1.6.3 
lib/ant/lib/ant-stylebook.jar                     | ant:ant-stylebook:1.6.3 
lib/ant/lib/ant-swing.jar                         | ant:ant-swing:1.6.3 
lib/ant/lib/ant-trax.jar                          | ant:ant-trax:1.6.3 
lib/ant/lib/ant-vaj.jar                           | ant:ant-vaj:1.6.3 
lib/ant/lib/ant-weblogic.jar                      | ant:ant-weblogic:1.6.3 
lib/ant/lib/ant-xalan1.jar                        | ant:ant-xalan1:1.6.3 
lib/ant/lib/ant-xslp.jar                          | ant:ant-xslp:1.6.3 
lib/ant/lib/ant.jar                               | ant:ant:1.6.3 
lib/ant/lib/junit.jar                             | junit:junit:3.8.1 
lib/ant/lib/xercesImpl.jar                        | xerces:xercesImpl:2.6.2 
lib/ant/lib/xml-apis.jar                          | xerces:xmlParserAPIs:2.6.2 
lib/asm/asm-2.0.jar                               | 
lib/asm/asm-9.1.jar                               | org.ow2.asm:asm:9.1 
lib/asm/asm-9.1.renamed.jar                       | 
lib/aspectj/lib/aspectjrt.jar                     | 
lib/aspectj/lib/aspectjrt121.jar                  | aspectj:aspectjrt:1.2.1 
lib/aspectj/lib/aspectjtools.jar                  | 
lib/bcel/bcel-src.zip                             | 
lib/bcel/bcel-verifier-src.zip                    | 
lib/bcel/bcel-verifier.jar                        | 
lib/bcel/bcel.jar                                 | 
lib/build/build.jar                               | 
lib/build/build.old.jar                           | 
lib/commons/commons-src.zip                       | 
lib/commons/commons.jar                           | 
lib/docbook/docbook-xsl/extensions/saxon642.jar   | 
lib/docbook/docbook-xsl/extensions/saxon643.jar   | 
lib/docbook/docbook-xsl/extensions/xalan2.jar     | 
lib/docbook/fop/avalon-framework-cvs-20020806.jar | 
lib/docbook/fop/batik.jar                         | batik:batik-1.5-fop:0.20-5 
lib/docbook/fop/fop.jar                           | fop:fop:0.20.5 
lib/docbook/fop/xalan.jar                         | xalan:xalan:2.4.1 
lib/ext/jrockit/jrockit-src.zip                   | 
lib/ext/jrockit/jrockit.jar                       | 
lib/ext/jrockit/managementapi-jrockit81.jar       | 
lib/jarjar/jarjar-1.3.jar                         | com.googlecode.jarjar:jarjar:1.3 
lib/jdiff/jdiff.jar                               | 
lib/junit/junit-src.zip                           | junit:junit:3.8.1 
lib/junit/junit.jar                               | junit:junit:3.8.1 
lib/jython/jython.jar                             | jython:jython:2.1 
lib/regexp/jakarta-regexp-1.2.jar                 | regexp:regexp:1.2 
lib/saxon/saxon.jar                               | 
lib/test/aspectjrt.jar                            | 
lib/test/loadtime5.jar                            | 
lib/test/testing-client.jar                       | 
```

We see many artifacts available on Maven Central, but also quite a few missing ones. Let us talk about them step by step as I find out more.

**Comment by kriegaex** [comment]
When searching the code base for all POMs containing something like

```xml
<scope>system</scope>
<systemPath>${project.basedir}/../<some_path>/<some_artifact>.jar</systemPath>
```

I find the following unique ones:

```none
$ find -name 'pom.xml' | xargs grep -E '<systemPath>' | sed -E 's#.*[.][.]/((.*)[.]jar).*#\1#' | sort | uniq
lib/ant/lib/ant-launcher.jar
lib/ant/lib/ant.jar
lib/ant/lib/xercesImpl.jar
lib/ant/lib/xml-apis.jar
lib/asm/asm-9.1.renamed.jar
lib/commons/commons.jar
lib/ext/jrockit/jrockit.jar
lib/jdiff/jdiff.jar
lib/regexp/jakarta-regexp-1.2.jar
org.eclipse.jdt.core/jdtcore-for-aspectj.jar
```

I.e. we see Maven dependencies on
  * 4 libraries from the Ant distribution (more about Ant in the next comment, stay tuned) which are all available on Maven Central,
  * a version of ASM also available on Maven Central with package names relocated to `aj.org.objectweb`, which we could easily recreate using Maven Shade plugin, because that plugin knows how to relocate both binary and source JARs,
  * a probably home-brew version of some old Apache Commons libraries (Beanutils, Collections, Digester, Logging), zipped into one,
  * home-brew archives of some JRockit 8.1 libraries,
  * an old version of a diffing tool called JDiff we use to compare test console output to what we expect to see,
  * Jakarta Regexp 1.2
  * and of course JDT Core for AspectJ, which currently is deployed by AspectJ itself instead of by the JDT Core "shadows" project, as it should be. Then the AspectJ build could just use it as a normal dependency.

So we need to find out more about if and where to find download sources for libraries containing
  * the original versions of the 4 tools contained in the Apache Commons compilation,
  * the JRockit binaries (if JRockit support is still relevant in AspectJ, I have no idea),
  * JDiff.

The origins of the rest are clear. The worst case would be to deploy the missing ones as separate artifacts somewhere, so the Maven build finds them and we can eliminate them from the Git repository.

**Comment by kriegaex** [comment]
The `libs/ant` directory is special insofar as it contains a full Ant installation consisting of binaries, shell scripts, text files and JARs. More precisely, it contains Ant 1.6.3.

In addition to that, the directory contains
  * a home-brew source ZIP for Ant,
  * an AspectJ-specific read-me file,
  * a copy of the JUnit 3.8.1 named `lib/junit/junit.jar` which is absolutely identical to `lib/junit/junit.jar` (if you search for the SHA-1 checksum 99129f16442844f6a4a11ae22fbbee40b14d774f in the curl script above, you will notice that it actually checks for the same binary on Maven Central twice, exactly this one).

Now I have good news and bad news:
  * The good news is that both Ant 1.6.3 binaries and sources are available as downloads.
  * The bad news is that those downloads are on an Apache web server, not on Maven Central.

This is not a big problem because we can use [Maven Download Plugin](https://github.com/maven-download-plugin/maven-download-plugin) and its WGet goal in order to download those files. The plugin even has an option to compare each download to an expected checksum. I do not think the latter is necessary, but it would be easy enough to add as an option.

The download sources are:
  * [Ant 1.6.3 binary distribution](https://archive.apache.org/dist/ant/binaries/apache-ant-1.6.3-bin.zip), as found on the [Ant binaries download page](https://ant.apache.org/bindownload.cgi), then click on "Old Ant Releases".
  * [Ant 1.6.3 source code](https://archive.apache.org/dist/ant/source/apache-ant-1.6.3-src.zip), as found on the [Ant sources download page](https://ant.apache.org/srcdownload.cgi), then click on "Old Ant Releases".

Now for the anatomy of those two download archives, compared to the content stored in the AspectJ SCM under `lib/ant`. I did a full directory tree compare and found out the following:
  * The contents of the binary distribution are identical to `lib/ant`, with these exceptions:
    * the zip folder `docs` does not exist in `lib/ant` → no problem (we never committed the docs)
    * `lib/ant/aspectj-ant-readme.txt` → no problem (additional AspectJ read-me, see above)
    * `lib/ant/ant-src.zip` → no problem, we got that covered (see below)
    * `lib/ant/lib/junit.jar` → no problem (is `junit:junit:3.8.1`, see above)
    * The only differences I saw while diffing complete directory trees, were CRLF vs LF line break differences, probably because I checked out on Windows. After a `dos2unix` on all the text files (except for Windows batch files *.bat, *.cmd), they were exactly identical to the zip contents.
  * The source distribution contains a superset of information compared to the source zip stored in AspectJ. When comparing just the zip subfolder `apache-ant-1.6.3/src/main` to `lib/ant/ant-src.zip`, the contents are exactly identical.

What this means is that
  * we have a way to completely recreate the 'lib/ant' folder with content downloaded from official sources, (**update:**) without the need to define all 33 sub-libraries contained in the binary distribution separately,
  * plus we replace the 4 Ant libraries used as Maven system dependencies mentioned a while ago by normal Maven dependencies. That the same 4 files also exist in `lib/ant` after unpacking the binary distribution, does not matter. Ant called in batch mode can still use them from there.

**Comment by aclement** [comment]
How about we get rid of ant

**Comment by kriegaex** [comment]
> How about we get rid of ant

That is a bigger job, because many tests run Ant builds and we would have to replace `AntSpec` by a new `MavenSpec` and then refactor all test specifications using `<ant />` to use the hypothetical `<maven/ >` instead. But that is not all, because each of those tests refers to an actual Ant _build.xml_ which would also have to be replaced.

Right now I do not feel so inclined to do that on my own. Furthermore, I managed to get rid of the committed `lib/ant` and several other committed third-party dependencies and download them dynamically from Maven Central, GitHub Packages or other websites (Apache, SourceForge) already. See next message.

**Comment by kriegaex** [comment]
I think I have reached a stage in #41 where we could think about merging. I managed to get rid of all system-scoped dependencies and several `lib` subdirectories:
  * `lib/ant`: Downloaded incl. source code and unzipped exactly to the state it was in before, even copying over the redundant JUnit library from `lib/junit`.
  * `lib/asm`: Transformed into a separate Maven module which has the AspectJ parent as its parent, too, but is not a `<module>`. It builds separately, dynamically relocating the **ASM** classes to the AspectJ package name space, and can also deploy the result (including relocated sources) to GitHub Packages. The main AspectJ build just uses it as a normal dependency, using an additional `<repository>` entry for my GitHub Packages repository. If necessary, this can be migrated to an Eclipse-owned repo in the future.
  * `lib/commons`: Was a mix of 4 different vintage Apache Commons libraries, all zipped into one, of which only 2 are actively used in the AspectJ test code. So I replaced this system dependency by fine-granular ones where they are needed, but also recreated the compound JAR and even the sources JAR by the actual versions used in AspectJ. Finding those and all the other matching versions was quite difficult, because I had to search project archives and look into SCMs.
  * `lib/jarjar`: Downloaded and copied over, similar to Ant, just less complicated.
  * `lib/jdtcore-aj`: This new subdirectory replaces the former submodule `org.aspectj:org.eclipse.jdt.core` which I deleted completely in favour of a new Maven build in **JDT Core Shadows**, which also deploys to GitHub Packages, similar to our ASM artifact. The Ant script building JDT Core Shadows and copying it over into the AspectJ project directory is obsolete now (but the script still exists).
  * `lib/junit`: Downloaded and copied over, similar to Ant, just less complicated.
  * `lib/jython`: Completely removed because it was not used anywhere in AspectJ builds or tests.
  * `lib/regexp`: Downloaded and copied over, similar to Ant, just less complicated.
  * `lib/saxon`: Downloaded and copied over, similar to Ant, just less complicated.

One more system-scoped dependency I got rid of was **JRockit**, see https://github.com/eclipse/org.aspectj/pull/41/commits/f3ff0752.

**Comment by kriegaex** [comment]
The new `lib/pom.xml` is a separate Maven module which has the AspectJ parent as its parent, too, but is not a `<module>`. It builds separately. After cloning a fresh copy of AspectJ, this module has to be built once via `cd lib && mvn compile`. It will download and install all missing files expected to be in the `lib` folder. After that, can be built AspectJ normally. In case a developer forgets this step, a Maven Enforcer rule in the main project will check for the existence of several files and fail the build if they are missing, also explaining to the user how to prepare the project. I hope that this is quite fool-proof.

**Comment by kriegaex** [comment]
Update:
  * `lib/docbooks`: Two libraries as well as docbooks-xsl and docbooks-dtd distributions - all needed to generate AspectJ HTML documentation from DocBook sources - are now downloaded dynamically, i.e. the whole folder is completely obsolete in the SCM and was deleted.

I.e. as of now only these folders are still remaining and to be investigated with regard to being needed (at all and where exactly) and how to replace the contained binaries by downloads:
  * `lib/aspectj/lib`
  * `lib/bcel`
  * `lib/build`
  * `lib/test`

@aclement, I would appreciate some background information about the remaining folders. Especially the various AspectJ libraries in `lib/aspectj/lib` and `lib/test` would be interesting. There even exist almost identical `aspectjrt.jar` versions in both folders, one from 1.8.2 and one 1.9.3 or so. Furthermore, an old `aspectjrt121.jar` exists, too. Do we really need them all? Same goes for the other libraries. I would like to know their exact purposes, if we can get rid of some or download them instead etc.

**Comment by kriegaex** [comment]
The stuff mentioned in my previous comment is still in the SCM due to lack of feedback. So there is still some work left, eliminating stuff which we pssibly do not need in the SCM. Maybe I am going to fork off another issue for it.
