### ISSUE TITLE
pointcut on the If() statements

### ISSUE THREAD

**Issue by abolfazl-sh** [eclipse-aspectj/aspectj#47]
Hi.
does it possible pointcut on If() statements?
for example we have below code : 

```
package paj;
public class a {
	private static final String FILE_PATH = ".\\Code Data\\calday.java";
	
	public static void main(String[] args) {
			int z = 2;
                        int j = 20;
			if(z == 22) {
                          //do something
                        }

                        if(j  == 20){
                          //do another thing
                       }
     }
}
```

as we can see always second( if(j==20)) run.
does it possible to write an aspect which every time any condition was true do something(in this example the second condition(if(j==20)) is true so print the line of code.

**Comment by aclement** [comment]
That kind of setup is unfortunately not a join point upon which you can match with a point cut. If it were more like:

```
public static void main(String []argv) {
if (j.equals(20)) {
...
}
}
```
then that is a call to the method equals which can be identified (something like `call(* equals(..)) && withincode(* main(..))`). Or if it was:
```
if (isEqual(j,20)) {
```
A similar call point cut could catch it, but the pure `==` is hard to identify and match based on how it manifests in the bytecode. We don't have a way to describe how these expressions manifest in the source.
