### ISSUE TITLE
Special config for applying aspect to maven dependency?

### ISSUE THREAD

**Issue by MarkFullerEB** [eclipse-aspectj/aspectj#94]
Is there any sort of special configuration that needs to happen when applying an aspect to a maven dependency?
I'm trying to add an `@Around` to `@Slf4j` library whenever I call `.info(String)` or `.error(String)`. However nothing I do will call the aspect. The signature of my aspect is the following 

```java
@Aspect
@Component
public class LoggingAspect {

    @Around("execution(* ch.qos.logback.classic.Logger.*(..))")
    public Object prependBridgeRunId(ProceedingJoinPoint jp) throws Throwable {
```
I have other aspects working in the project so I know its not some aspectJ library issue. 
Any pointers are welcome. Thank you!

**Comment by kriegaex** [comment]
This is neither a bug report nor a feature request. It is not about AspectJ as such but about AspectJ Maven Plugin, as it seems. Please ask this kind of question on stackoverflow.com and add the `aspectj` and `aspectj-maven-plugin` tags, then I will find it. Please also provide a minimal Maven project with aspect and simple Java application, if possible. I am going to answer your question there. 

Thank you, see you on SO. 🙂
