### ISSUE TITLE
ajc ant task dos not support JDK16 and JDK17

### ISSUE THREAD

**Issue by urferr** [eclipse-aspectj/aspectj#97]
The class org.aspectj.tools.ant.taskdefs.AjcTask contains the 2 static attributes TARGET_INPUTS and SOURCE_INPUTS containing the known JDK version strings. Unfortunately these 2 variables have not been upgraded in aspectj 1.9.7 and not in the current 1.9.8.RC2 with the result that JDK 16 and JDK 17 both are not supported when using the ant task to compile an aspect.

Because we need a gradle plugin based on ant this makes it impossible to build aspectj projects with targetCompatibility =17

**Comment by kriegaex** [comment]
I have never used Ant for building AspectJ projects myself, being a Maven guy. Would you please be so kind as to attach a minimal test project which I can use in order to reproduce the issue? That would speed up things. Thank you.

**Update:** Are you talking about this part? https://github.com/eclipse/org.aspectj/blob/67b1c353a02c335074a736ebf76a49bf24eefb19/taskdefs/src/main/java/org/aspectj/tools/ant/taskdefs/AjcTask.java#L253-L255

Yeah, it seems to be pretty obvious that Java 16 and 17 are missing there.

**Comment by urferr** [comment]
Adding a test project will be hard because the gradle plugin we use is an internal one and you have no access to it.

Yes, i mean these 3 lines, everywhere "16", "17" is missing and thefore only source/targetCompatibility up to JDK 15 is supported. When i now define JDK 16 or 17 as compatibility version it takes the internal default one which i guest is JDK 1.4 and then the compiler fails whaen annotations are used because they were not supported in Java 1.4

I also guess that in the definition of COMPLIANCE_INPUTS the values should be "-15", "-16", "-17"

**Comment by kriegaex** [comment]
I do not need your Gradle project. I was thinking about the AspectJ project you are indirectly building with it, using the AspectJ Ant task. Just an [MCVE](https://stackoverflow.com/help/mcve) version of it to reproduce the error and verify the bugfix, not your original project.

**Comment by kriegaex** [comment]
I quickly fixed the static lists of strings and deployed a snapshot to the Sonatype OSSRH snapshot repository. Please temporarily configure your project to use AspectJ 1.9.8-SNAPSHOT and add the equivalent of this Maven setting to your Gradle build:

```xml
<repositories>
  <repository>
    <id>ossrh-snapshots</id>
    <name>Sonatype OSSRH snapshots</name>
    <url>https://oss.sonatype.org/content/repositories/snapshots</url>
    <layout>default</layout>
    <snapshots>
      <enabled>true</enabled>
      <updatePolicy>always</updatePolicy>
    </snapshots>
    <releases>
      <enabled>true</enabled>
      <updatePolicy>never</updatePolicy>
    </releases>
  </repository>
</repositories>
```

Then you can test by yourself and I do not need the MCVE project from you.

**Comment by urferr** [comment]
[AspectjBug.zip](https://github.com/eclipse/org.aspectj/files/7538601/AspectjBug.zip)

This attachment contains a simple project to reproduce the problem. Currently the source and target version in the build-xml ant script are set to 17 and if you run the build target "compile" you get an error. The same error happens if you change source and target version to "16".
Everything build fine if you change soource and target to "15".

Hope this helps.

**Comment by kriegaex** [comment]
I can confirm that after downloading the snapshots and copying them into your `lib` directory, it works:

```none
$ ant compile
Buildfile: ...\AspectjBug\build.xml

compile:

BUILD SUCCESSFUL
Total time: 1 second

$ javap -v build/compile/ant/*.class | grep major
  major version: 61
  major version: 61
```

The class file major versions also prove that the compiled class files are really Java 17 files.

I hope you can live with the snapshot version until the next release candidate or final release.

**Comment by kriegaex** [comment]
@urferr: FYI, AspectJ 1.9.8.RC3 is available on Maven Central. It also contains the bugfix for the Ant task.
